name = "maintenance-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "maintenance-db"
database_id = "736b090b-05f3-4330-aa7f-7c69bf309c61"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "maintenance-images"
